[workspace]
resolver = "3"
members = [
    "crates/lex-sys-syntax",
    "crates/lex-sys-types",
    "crates/lex-sys-id",
    "crates/lex-sys-ir",
    "crates/lex-sys-codegen",
    "crates/lex-sys-codegen-llvm",
    "crates/lex-sys-vcs",
    "crates/lex-sys",
]

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
license = "EUPL-1.2"
publish = false

[workspace.dependencies]
lex-sys-syntax = { path = "crates/lex-sys-syntax" }
lex-sys-types = { path = "crates/lex-sys-types" }
lex-sys-id = { path = "crates/lex-sys-id" }
lex-sys-ir = { path = "crates/lex-sys-ir" }
lex-sys-codegen = { path = "crates/lex-sys-codegen" }
lex-sys-codegen-llvm = { path = "crates/lex-sys-codegen-llvm" }
lex-sys-vcs = { path = "crates/lex-sys-vcs" }
