[package]
name = "lex-sys"
description = "The lex-sys bootstrap compiler CLI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "lex-sys"
path = "src/main.rs"

[dependencies]
lex-sys-syntax.workspace = true
lex-sys-ir.workspace = true
lex-sys-codegen.workspace = true
